/*
 * Copyright (c) 2024 Nuvoton Technology Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_GPIO_NUVOTON_NPCM_GPIO_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_GPIO_NUVOTON_NPCM_GPIO_H_

/* NPCM wake-up input source offset calculation */
#define NPCM_MIWU_TABLE_SHIFT     (6)
#define NPCM_MIWU_TABLE_MASK      (0x3)
#define NPCM_MIWU_TABLE_OFFSET(N) (((N) & NPCM_MIWU_TABLE_MASK) << NPCM_MIWU_TABLE_SHIFT)
#define NPCM_MIWU_GROUP_SHIFT     (3)
#define NPCM_MIWU_GROUP_MASK      ((1 << (NPCM_MIWU_TABLE_SHIFT - NPCM_MIWU_GROUP_SHIFT)) - 1)
#define NPCM_MIWU_GROUP_OFFSET(N) (((N) & NPCM_MIWU_GROUP_MASK) << NPCM_MIWU_GROUP_SHIFT)
#define NPCM_MIWU_BIT_MASK        ((1 << NPCM_MIWU_GROUP_SHIFT) - 1)
#define NPCM_MIWU_BIT_OFFSET(N)   ((N) & NPCM_MIWU_BIT_MASK)
#define NPCM_MIWU_IDX(table, group, bit)                                                           \
	(NPCM_MIWU_TABLE_OFFSET(table) + NPCM_MIWU_GROUP_OFFSET(group) + NPCM_MIWU_BIT_OFFSET(bit))

/*
 * Device input wakeup external interrupt source index.
 * 3 tables and 8 groups (groupA to H) for each table.
 */
/* MIWU0: GROUP A */
#define NPCM_MIWU0_GROUPA_GPIO00 NPCM_MIWU_IDX(0, 0, 0)
#define NPCM_MIWU0_GROUPA_GPIO01 NPCM_MIWU_IDX(0, 0, 1)
#define NPCM_MIWU0_GROUPA_GPIO02 NPCM_MIWU_IDX(0, 0, 2)
#define NPCM_MIWU0_GROUPA_GPIO03 NPCM_MIWU_IDX(0, 0, 3)
#define NPCM_MIWU0_GROUPA_GPIO04 NPCM_MIWU_IDX(0, 0, 4)
#define NPCM_MIWU0_GROUPA_GPIO05 NPCM_MIWU_IDX(0, 0, 5)
#define NPCM_MIWU0_GROUPA_GPIO06 NPCM_MIWU_IDX(0, 0, 6)
#define NPCM_MIWU0_GROUPA_GPIO07 NPCM_MIWU_IDX(0, 0, 7)

/* MIWU0: GROUP B */
#define NPCM_MIWU0_GROUPB_GPIO10 NPCM_MIWU_IDX(0, 1, 0)
#define NPCM_MIWU0_GROUPB_GPIO11 NPCM_MIWU_IDX(0, 1, 1)
#define NPCM_MIWU0_GROUPB_GPIO12 NPCM_MIWU_IDX(0, 1, 2)
#define NPCM_MIWU0_GROUPB_GPIO13 NPCM_MIWU_IDX(0, 1, 3)
#define NPCM_MIWU0_GROUPB_GPIO14 NPCM_MIWU_IDX(0, 1, 4)
#define NPCM_MIWU0_GROUPB_GPIO15 NPCM_MIWU_IDX(0, 1, 5)
#define NPCM_MIWU0_GROUPB_GPIO16 NPCM_MIWU_IDX(0, 1, 6)
#define NPCM_MIWU0_GROUPB_GPIO17 NPCM_MIWU_IDX(0, 1, 7)

/* MIWU0: GROUP C */
#define NPCM_MIWU0_GROUPC_GPIO20 NPCM_MIWU_IDX(0, 2, 0)
#define NPCM_MIWU0_GROUPC_GPIO21 NPCM_MIWU_IDX(0, 2, 1)
#define NPCM_MIWU0_GROUPC_GPIO22 NPCM_MIWU_IDX(0, 2, 2)
#define NPCM_MIWU0_GROUPC_GPIO23 NPCM_MIWU_IDX(0, 2, 3)
#define NPCM_MIWU0_GROUPC_GPIO24 NPCM_MIWU_IDX(0, 2, 4)
#define NPCM_MIWU0_GROUPC_GPIO25 NPCM_MIWU_IDX(0, 2, 5)
#define NPCM_MIWU0_GROUPC_GPIO26 NPCM_MIWU_IDX(0, 2, 6)
#define NPCM_MIWU0_GROUPC_GPIO27 NPCM_MIWU_IDX(0, 2, 7)

/* MIWU0: GROUP D */
#define NPCM_MIWU0_GROUPD_GPIO30 NPCM_MIWU_IDX(0, 3, 0)
#define NPCM_MIWU0_GROUPD_GPIO31 NPCM_MIWU_IDX(0, 3, 1)
#define NPCM_MIWU0_GROUPD_GPIO32 NPCM_MIWU_IDX(0, 3, 2)
#define NPCM_MIWU0_GROUPD_GPIO33 NPCM_MIWU_IDX(0, 3, 3)
#define NPCM_MIWU0_GROUPD_GPIO34 NPCM_MIWU_IDX(0, 3, 4)
#define NPCM_MIWU0_GROUPD_GPIO35 NPCM_MIWU_IDX(0, 3, 5)
#define NPCM_MIWU0_GROUPD_GPIO36 NPCM_MIWU_IDX(0, 3, 6)
#define NPCM_MIWU0_GROUPD_GPIO37 NPCM_MIWU_IDX(0, 3, 7)

/* MIWU0: GROUP E */
#define NPCM_MIWU0_GROUPE_GPIO40 NPCM_MIWU_IDX(0, 4, 0)
#define NPCM_MIWU0_GROUPE_GPIO41 NPCM_MIWU_IDX(0, 4, 1)
#define NPCM_MIWU0_GROUPE_GPIO42 NPCM_MIWU_IDX(0, 4, 2)
#define NPCM_MIWU0_GROUPE_GPIO43 NPCM_MIWU_IDX(0, 4, 3)
#define NPCM_MIWU0_GROUPE_GPIO44 NPCM_MIWU_IDX(0, 4, 4)
#define NPCM_MIWU0_GROUPE_GPIO45 NPCM_MIWU_IDX(0, 4, 5)
#define NPCM_MIWU0_GROUPE_GPIO46 NPCM_MIWU_IDX(0, 4, 6)
#define NPCM_MIWU0_GROUPE_GPIO47 NPCM_MIWU_IDX(0, 4, 7)

/* MIWU0: GROUP F */
#define NPCM_MIWU0_GROUPF_GPIO50 NPCM_MIWU_IDX(0, 5, 0)
#define NPCM_MIWU0_GROUPF_GPIO51 NPCM_MIWU_IDX(0, 5, 1)
#define NPCM_MIWU0_GROUPF_GPIO52 NPCM_MIWU_IDX(0, 5, 2)
#define NPCM_MIWU0_GROUPF_GPIO53 NPCM_MIWU_IDX(0, 5, 3)
#define NPCM_MIWU0_GROUPF_GPIO54 NPCM_MIWU_IDX(0, 5, 4)
#define NPCM_MIWU0_GROUPF_GPIO55 NPCM_MIWU_IDX(0, 5, 5)
#define NPCM_MIWU0_GROUPF_GPIO56 NPCM_MIWU_IDX(0, 5, 6)
#define NPCM_MIWU0_GROUPF_GPIO57 NPCM_MIWU_IDX(0, 5, 7)

/* MIWU0: GROUP G */
#define NPCM_MIWU0_GROUPG_GPIO60 NPCM_MIWU_IDX(0, 6, 0)
#define NPCM_MIWU0_GROUPG_GPIO61 NPCM_MIWU_IDX(0, 6, 1)
#define NPCM_MIWU0_GROUPG_GPIO62 NPCM_MIWU_IDX(0, 6, 2)
#define NPCM_MIWU0_GROUPG_GPIO63 NPCM_MIWU_IDX(0, 6, 3)
#define NPCM_MIWU0_GROUPG_GPIO64 NPCM_MIWU_IDX(0, 6, 4)
#define NPCM_MIWU0_GROUPG_GPIO65 NPCM_MIWU_IDX(0, 6, 5)
#define NPCM_MIWU0_GROUPG_GPIO66 NPCM_MIWU_IDX(0, 6, 6)
#define NPCM_MIWU0_GROUPG_GPIO67 NPCM_MIWU_IDX(0, 6, 7)

/* MIWU0: GROUP H */
#define NPCM_MIWU0_GROUPH_GPIO70 NPCM_MIWU_IDX(0, 7, 0)
#define NPCM_MIWU0_GROUPH_GPIO71 NPCM_MIWU_IDX(0, 7, 1)
#define NPCM_MIWU0_GROUPH_GPIO72 NPCM_MIWU_IDX(0, 7, 2)
#define NPCM_MIWU0_GROUPH_GPIO73 NPCM_MIWU_IDX(0, 7, 3)
#define NPCM_MIWU0_GROUPH_GPIO74 NPCM_MIWU_IDX(0, 7, 4)
#define NPCM_MIWU0_GROUPH_GPIO75 NPCM_MIWU_IDX(0, 7, 5)
#define NPCM_MIWU0_GROUPH_GPIO76 NPCM_MIWU_IDX(0, 7, 6)
#define NPCM_MIWU0_GROUPH_GPIO77 NPCM_MIWU_IDX(0, 7, 7)

/* MIWU1: GROUP A */
#define NPCM_MIWU1_GROUPA_GPIO80 NPCM_MIWU_IDX(1, 0, 0)
#define NPCM_MIWU1_GROUPA_GPIO81 NPCM_MIWU_IDX(1, 0, 1)
#define NPCM_MIWU1_GROUPA_GPIO82 NPCM_MIWU_IDX(1, 0, 2)
#define NPCM_MIWU1_GROUPA_GPIO83 NPCM_MIWU_IDX(1, 0, 3)
#define NPCM_MIWU1_GROUPA_GPIO84 NPCM_MIWU_IDX(1, 0, 4)
#define NPCM_MIWU1_GROUPA_GPIO85 NPCM_MIWU_IDX(1, 0, 5)
#define NPCM_MIWU1_GROUPA_GPIO86 NPCM_MIWU_IDX(1, 0, 6)
#define NPCM_MIWU1_GROUPA_GPIO87 NPCM_MIWU_IDX(1, 0, 7)

/* MIWU1: GROUP B */
#define NPCM_MIWU1_GROUPB_GPIO90 NPCM_MIWU_IDX(1, 1, 0)
#define NPCM_MIWU1_GROUPB_GPIO91 NPCM_MIWU_IDX(1, 1, 1)
#define NPCM_MIWU1_GROUPB_GPIO92 NPCM_MIWU_IDX(1, 1, 2)
#define NPCM_MIWU1_GROUPB_GPIO93 NPCM_MIWU_IDX(1, 1, 3)
#define NPCM_MIWU1_GROUPB_GPIO94 NPCM_MIWU_IDX(1, 1, 4)
#define NPCM_MIWU1_GROUPB_GPIO95 NPCM_MIWU_IDX(1, 1, 5)
#define NPCM_MIWU1_GROUPB_GPIO96 NPCM_MIWU_IDX(1, 1, 6)
#define NPCM_MIWU1_GROUPB_GPIO97 NPCM_MIWU_IDX(1, 1, 7)

/* MIWU1: GROUP C */
#define NPCM_MIWU1_GROUPC_GPIOA0 NPCM_MIWU_IDX(1, 2, 0)
#define NPCM_MIWU1_GROUPC_GPIOA1 NPCM_MIWU_IDX(1, 2, 1)
#define NPCM_MIWU1_GROUPC_GPIOA2 NPCM_MIWU_IDX(1, 2, 2)
#define NPCM_MIWU1_GROUPC_GPIOA3 NPCM_MIWU_IDX(1, 2, 3)
#define NPCM_MIWU1_GROUPC_GPIOA4 NPCM_MIWU_IDX(1, 2, 4)
#define NPCM_MIWU1_GROUPC_GPIOA5 NPCM_MIWU_IDX(1, 2, 5)
#define NPCM_MIWU1_GROUPC_GPIOA6 NPCM_MIWU_IDX(1, 2, 6)
#define NPCM_MIWU1_GROUPC_GPIOA7 NPCM_MIWU_IDX(1, 2, 7)

/* MIWU1: GROUP D */
#define NPCM_MIWU1_GROUPD_CDBGPWRUPREQ     NPCM_MIWU_IDX(1, 3, 4)
#define NPCM_MIWU1_GROUPD_PC_EV_WKU        NPCM_MIWU_IDX(1, 3, 5)
#define NPCM_MIWU1_GROUPD_HOST_ACC         NPCM_MIWU_IDX(1, 3, 6)
#define NPCM_MIWU1_GROUPD_PLT_RST_ESPI_RST NPCM_MIWU_IDX(1, 3, 7)

/* MIWU1: GROUP E */
#define NPCM_MIWU1_GROUPE_EMAC  NPCM_MIWU_IDX(1, 4, 0)
#define NPCM_MIWU1_GROUPE_MSWC  NPCM_MIWU_IDX(1, 4, 2)
#define NPCM_MIWU1_GROUPE_T0OUT NPCM_MIWU_IDX(1, 4, 3)

/* MIWU1: GROUP F */
#define NPCM_MIWU1_GROUPF_GPIOB0 NPCM_MIWU_IDX(1, 5, 0)
#define NPCM_MIWU1_GROUPF_GPIOB1 NPCM_MIWU_IDX(1, 5, 1)
#define NPCM_MIWU1_GROUPF_GPIOB2 NPCM_MIWU_IDX(1, 5, 2)
#define NPCM_MIWU1_GROUPF_GPIOB3 NPCM_MIWU_IDX(1, 5, 3)
#define NPCM_MIWU1_GROUPF_GPIOB4 NPCM_MIWU_IDX(1, 5, 4)
#define NPCM_MIWU1_GROUPF_GPIOB5 NPCM_MIWU_IDX(1, 5, 5)
#define NPCM_MIWU1_GROUPF_GPIOB6 NPCM_MIWU_IDX(1, 5, 6)
#define NPCM_MIWU1_GROUPF_GPIOB7 NPCM_MIWU_IDX(1, 5, 7)

/* MIWU1: GROUP G */
#define NPCM_MIWU1_GROUPG_I3C1_2 NPCM_MIWU_IDX(1, 6, 7)

/* MIWU1: GROUP H */
#define NPCM_MIWU1_GROUPH_SMB1 NPCM_MIWU_IDX(1, 7, 1)
#define NPCM_MIWU1_GROUPH_SMB3 NPCM_MIWU_IDX(1, 7, 3)
#define NPCM_MIWU1_GROUPH_SMB4 NPCM_MIWU_IDX(1, 7, 4)
#define NPCM_MIWU1_GROUPH_SMB5 NPCM_MIWU_IDX(1, 7, 5)
#define NPCM_MIWU1_GROUPH_SMB6 NPCM_MIWU_IDX(1, 7, 6)
#define NPCM_MIWU1_GROUPH_RTC  NPCM_MIWU_IDX(1, 7, 7)

/* MIWU2: GROUP A */
#define NPCM_MIWU2_GROUPA_VW020_SLP_S3_L NPCM_MIWU_IDX(2, 0, 0)
#define NPCM_MIWU2_GROUPA_VW021_SLP_S4_L NPCM_MIWU_IDX(2, 0, 1)
#define NPCM_MIWU2_GROUPA_VW022_SLP_S5_L NPCM_MIWU_IDX(2, 0, 2)
#define NPCM_MIWU2_GROUPA_SUS_STAT_L     NPCM_MIWU_IDX(2, 0, 4)
#define NPCM_MIWU2_GROUPA_PLTRST_L       NPCM_MIWU_IDX(2, 0, 5)
#define NPCM_MIWU2_GROUPA_OOB_RST_WARN   NPCM_MIWU_IDX(2, 0, 6)

/* MIWU2: GROUP B */
#define NPCM_MIWU2_GROUPB_HOST_RST_WARN NPCM_MIWU_IDX(2, 1, 0)
#define NPCM_MIWU2_GROUPB_SUS_WARN_L    NPCM_MIWU_IDX(2, 1, 4)
#define NPCM_MIWU2_GROUPB_SUS_PWRDN_ACK NPCM_MIWU_IDX(2, 1, 5)
#define NPCM_MIWU2_GROUPB_SLP_A_L       NPCM_MIWU_IDX(2, 1, 7)

/* MIWU2: GROUP C */
#define NPCM_MIWU2_GROUPC_SLP_LAN_L       NPCM_MIWU_IDX(2, 2, 0)
#define NPCM_MIWU2_GROUPC_SLP_WLAN_L      NPCM_MIWU_IDX(2, 2, 1)
#define NPCM_MIWU2_GROUPC_PCH_TO_EC_GEN_0 NPCM_MIWU_IDX(2, 2, 4)
#define NPCM_MIWU2_GROUPC_PCH_TO_EC_GEN_1 NPCM_MIWU_IDX(2, 2, 5)
#define NPCM_MIWU2_GROUPC_PCH_TO_EC_GEN_2 NPCM_MIWU_IDX(2, 2, 6)
#define NPCM_MIWU2_GROUPC_PCH_TO_EC_GEN_3 NPCM_MIWU_IDX(2, 2, 7)

/* MIWU2: GROUP D */
#define NPCM_MIWU2_GROUPD_PCH_TO_EC_GEN_4 NPCM_MIWU_IDX(2, 3, 0)
#define NPCM_MIWU2_GROUPD_PCH_TO_EC_GEN_5 NPCM_MIWU_IDX(2, 3, 1)
#define NPCM_MIWU2_GROUPD_PCH_TO_EC_GEN_6 NPCM_MIWU_IDX(2, 3, 2)
#define NPCM_MIWU2_GROUPD_PCH_TO_EC_GEN_7 NPCM_MIWU_IDX(2, 3, 3)
#define NPCM_MIWU2_GROUPD_HOST_C10        NPCM_MIWU_IDX(2, 3, 4)

/* MIWU2: GROUP E */
#define NPCM_MIWU2_GROUPE_GPIOC0 NPCM_MIWU_IDX(2, 4, 0)
#define NPCM_MIWU2_GROUPE_GPIOC1 NPCM_MIWU_IDX(2, 4, 1)
#define NPCM_MIWU2_GROUPE_GPIOC2 NPCM_MIWU_IDX(2, 4, 2)
#define NPCM_MIWU2_GROUPE_GPIOC3 NPCM_MIWU_IDX(2, 4, 3)
#define NPCM_MIWU2_GROUPE_GPIOC4 NPCM_MIWU_IDX(2, 4, 4)
#define NPCM_MIWU2_GROUPE_GPIOC5 NPCM_MIWU_IDX(2, 4, 5)
#define NPCM_MIWU2_GROUPE_GPIOC6 NPCM_MIWU_IDX(2, 4, 6)
#define NPCM_MIWU2_GROUPE_GPIOC7 NPCM_MIWU_IDX(2, 4, 7)

/* MIWU2: GROUP F */
#define NPCM_MIWU2_GROUPF_GPIOD0 NPCM_MIWU_IDX(2, 5, 0)
#define NPCM_MIWU2_GROUPF_GPIOD1 NPCM_MIWU_IDX(2, 5, 1)
#define NPCM_MIWU2_GROUPF_GPIOD2 NPCM_MIWU_IDX(2, 5, 2)
#define NPCM_MIWU2_GROUPF_GPIOD3 NPCM_MIWU_IDX(2, 5, 3)
#define NPCM_MIWU2_GROUPF_GPIOD4 NPCM_MIWU_IDX(2, 5, 4)
#define NPCM_MIWU2_GROUPF_GPIOD5 NPCM_MIWU_IDX(2, 5, 5)
#define NPCM_MIWU2_GROUPF_GPIOD6 NPCM_MIWU_IDX(2, 5, 6)
#define NPCM_MIWU2_GROUPF_GPIOD7 NPCM_MIWU_IDX(2, 5, 7)

/* MIWU2: GROUP G */
#define NPCM_MIWU2_GROUPG_GPIOE0 NPCM_MIWU_IDX(2, 6, 0)
#define NPCM_MIWU2_GROUPG_GPIOE1 NPCM_MIWU_IDX(2, 6, 1)
#define NPCM_MIWU2_GROUPG_GPIOE2 NPCM_MIWU_IDX(2, 6, 2)
#define NPCM_MIWU2_GROUPG_GPIOE3 NPCM_MIWU_IDX(2, 6, 3)
#define NPCM_MIWU2_GROUPG_GPIOE4 NPCM_MIWU_IDX(2, 6, 4)
#define NPCM_MIWU2_GROUPG_GPIOE5 NPCM_MIWU_IDX(2, 6, 5)
#define NPCM_MIWU2_GROUPG_GPIOE6 NPCM_MIWU_IDX(2, 6, 6)

/* MIWU2: GROUP H */
#define NPCM_MIWU2_GROUPH_GPIOF0 NPCM_MIWU_IDX(2, 7, 0)
#define NPCM_MIWU2_GROUPH_GPIOF1 NPCM_MIWU_IDX(2, 7, 1)
#define NPCM_MIWU2_GROUPH_GPIOF2 NPCM_MIWU_IDX(2, 7, 2)
#define NPCM_MIWU2_GROUPH_GPIOF3 NPCM_MIWU_IDX(2, 7, 3)
#define NPCM_MIWU2_GROUPH_VCC    NPCM_MIWU_IDX(2, 7, 7)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_GPIO_NUVOTON_NPCM_GPIO_H_ */
